import React, { createContext, useState, useContext, ReactNode } from 'react';

// Define available languages
export type Language = 'en' | 'fr';

// Define translations
export const translations = {
  en: {
    // General
    dashboard: 'Dashboard',
    clients: 'Clients',
    products: 'Products',
    invoices: 'Invoices',
    quotes: 'Quotes',
    expenses: 'Expenses',
    reports: 'Reports',
    aiAssistant: 'AI Assistant',
    settings: 'Settings',
    logout: 'Log out',
    search: 'Search',
    add: 'Add',
    edit: 'Edit',
    delete: 'Delete',
    cancel: 'Cancel',
    save: 'Save',
    create: 'Create',
    update: 'Update',
    actions: 'Actions',
    status: 'Status',
    all: 'All',
    name: 'Name',
    email: 'Email',
    phone: 'Phone',
    address: 'Address',
    city: 'City',
    country: 'Country',
    date: 'Date',
    amount: 'Amount',
    total: 'Total',
    description: 'Description',
    category: 'Category',
    loading: 'Loading...',
    noResults: 'No results found',
    success: 'Success',
    error: 'Error',
    confirm: 'Confirm',
    view: 'View',
    download: 'Download',
    optional: 'Optional',
    draft: 'Draft',
    selectFile: 'Select File',
    openMenu: 'Open menu',
    currency: 'Currency',
    notes: 'Notes',
    price: 'Price',
    confirmDeletion: 'Confirm Deletion',
    actionCannotBeUndone: 'This action cannot be undone.',
    tryAgain: 'Try Again',
    
    // Dashboard
    welcomeBack: 'Welcome back',
    hereIsWhatsHappening: 'Here\'s what\'s happening with your business',
    fromLastMonth: 'from last month',
    newThisMonth: 'new this month',
    createdThisMonth: 'created this month',
    overdueInvoices: 'overdue invoices',
    recentInvoices: 'Recent Invoices',
    noRecentInvoices: 'No recent invoices',
    viewAllInvoices: 'View all invoices',
    aiInsights: 'AI Insights',
    personalizedBusinessRecommendations: 'Personalized business recommendations',
    generatingInsights: 'Generating insights...',
    noInsightsYet: 'No insights yet. Generate some insights to help your business grow.',
    generateInsights: 'Generate Insights',
    quickActions: 'Quick Actions',
    viewReports: 'View Reports',
    failedToLoadDashboard: 'Failed to load dashboard data',
    failedToGenerateInsights: 'Failed to generate insights',
    premiumPlan: 'Premium Plan',
    businessPlan: 'Business Plan',
    freePlan: 'Free Plan',
    
    // Admin
    adminDashboard: 'Admin Dashboard',
    userManagement: 'User Management',
    analytics: 'Analytics',
    users: 'Users',
    addUser: 'Add User',
    
    // Clients
    addClient: 'Add Client',
    editClient: 'Edit Client',
    manageClientsInfo: 'Manage your clients and their information',
    totalClients: 'Total Clients',
    noClientsFound: 'No clients found',
    clientCreatedSuccessfully: 'Client created successfully',
    clientUpdatedSuccessfully: 'Client updated successfully',
    clientDeletedSuccessfully: 'Client deleted successfully',
    failedToCreateClient: 'Failed to create client',
    failedToUpdateClient: 'Failed to update client',
    failedToDeleteClient: 'Failed to delete client',
    failedToFetchClients: 'Failed to fetch clients',
    fillClientDetails: 'Fill in the details to create a new client',
    updateClientDetails: 'Update client information',
    areYouSureDeleteClient: 'Are you sure you want to delete client',
    taxId: 'Tax ID / VAT',
    paymentTerms: 'Payment Terms',
    days: 'days',
    discount: 'Discount',
    location: 'Location',
    
    // Products
    addProduct: 'Add Product',
    editProduct: 'Edit Product',
    manageProductsInfo: 'Manage your products and inventory',
    totalProducts: 'total products',
    noProductsFound: 'No products found',
    productCreatedSuccessfully: 'Product created successfully',
    productUpdatedSuccessfully: 'Product updated successfully',
    productDeletedSuccessfully: 'Product deleted successfully',
    failedToCreateProduct: 'Failed to create product',
    failedToUpdateProduct: 'Failed to update product',
    failedToDeleteProduct: 'Failed to delete product',
    failedToFetchProducts: 'Failed to fetch products',
    fillProductDetails: 'Fill in the details to create a new product',
    updateProductDetails: 'Update product information',
    areYouSureDeleteProduct: 'Are you sure you want to delete product',
    unit: 'Unit',
    taxRate: 'Tax Rate',
    sku: 'SKU',
    stock: 'Stock',
    currentStock: 'Current Stock',
    minimumStock: 'Minimum Stock',
    cost: 'Cost',
    active: 'Active',
    
    // Quotes
    createQuote: 'Create Quote',
    quoteNumber: 'Quote Number',
    quoteDate: 'Quote Date',
    validUntil: 'Valid Until',
    quoteStatus: 'Status',
    quoteAmount: 'Amount',
    quoteItems: 'Quote Items',
    manageQuotes: 'Create and manage quotes for your clients',
    totalQuotes: 'total quotes',
    pending: 'Pending',
    accepted: 'Accepted',
    rejected: 'Rejected',
    expired: 'Expired',
    quoteDeletedSuccessfully: 'Quote deleted successfully',
    failedToDeleteQuote: 'Failed to delete quote',
    failedToFetchQuotes: 'Failed to fetch quotes',
    areYouSureDeleteQuote: 'Are you sure you want to delete quote',
    quoteDownloaded: 'Quote downloaded successfully',
    failedToGenerateQuotePDF: 'Failed to generate quote PDF',
    
    // Expenses
    addExpense: 'Add Expense',
    expenseDate: 'Expense Date',
    expenseCategory: 'Category',
    expenseAmount: 'Amount',
    paymentMethod: 'Payment Method',
    viewReceipt: 'View Receipt',
    manageExpenses: 'Track and manage your business expenses',
    totalExpensesCount: 'total expenses',
    expense: 'expense',
    expenseFound: 'expense found',
    expensesFound: 'expenses found',
    expenseDeletedSuccessfully: 'Expense deleted successfully',
    failedToDeleteExpense: 'Failed to delete expense',
    failedToFetchExpenses: 'Failed to fetch expenses',
    areYouSureDeleteExpense: 'Are you sure you want to delete this expense',
    uploadReceipt: 'Upload Receipt',
    downloadReceipt: 'Download Receipt',
    receiptUploaded: 'Receipt uploaded successfully',
    failedToUploadReceipt: 'Failed to upload receipt',
    
    // Reports
    financialReports: 'Financial Reports',
    salesReports: 'Sales Reports',
    clientReports: 'Client Reports',
    revenueReport: 'Revenue Report',
    expenseReport: 'Expense Report',
    profitReport: 'Profit Report',
    clientReport: 'Client Report',
    generateReport: 'Generate Report',
    totalSales: 'Total Sales',
    totalExpenses: 'Total Expenses',
    profit: 'Profit',
    profitMargin: 'Profit Margin',
    salesOverTime: 'Sales Over Time',
    expensesOverTime: 'Expenses Over Time',
    salesTrend: 'Sales Trend',
    expensesTrend: 'Expenses Trend',
    monthlySales: 'Monthly Sales',
    salesByMonth: 'Sales By Month',
    productSales: 'Product Sales',
    salesByProduct: 'Sales By Product',
    clientRevenue: 'Client Revenue',
    revenueByClient: 'Revenue By Client',
    clientDistribution: 'Client Distribution',
    revenueDistribution: 'Revenue Distribution',
    months: 'Months',
    year: 'Year',
    
    // AI Assistant
    generateContent: 'Generate Content',
    contentType: 'Content Type',
    prompt: 'Prompt',
    context: 'Context',
    recentGenerations: 'Recent Generations',
    copyToClipboard: 'Copy to Clipboard',
    copied: 'Copied!',
    emailTemplate: 'Email Template',
    marketingCopy: 'Marketing Copy',
    productDescription: 'Product Description',
    socialMediaPost: 'Social Media Post',
    blogPost: 'Blog Post',
    customContent: 'Custom Content',
    generate: 'Generate',
    generatingContent: 'Generating Content...',
    generatedOn: 'Generated on',
    
    // Invoice related
    createInvoice: 'Create Invoice',
    manageInvoicesAndTrackPayments: 'Manage your invoices and track payments',
    invoiceNumber: 'Invoice #',
    client: 'Client',
    dueDate: 'Due Date',
    allInvoices: 'All Invoices',
    allStatuses: 'All Statuses',
    filterByStatus: 'Filter by status',
    youHave: 'You have',
    totalInvoices: 'Total Invoices',
    noInvoicesFound: 'No invoices found',
    downloadPDF: 'Download PDF',
    sent: 'Sent',
    paid: 'Paid',
    overdue: 'Overdue',
    cancelled: 'Cancelled',
    areYouSureDelete: 'Are you sure you want to delete invoice',
    invoiceDeletedSuccessfully: 'Invoice deleted successfully',
    failedToDeleteInvoice: 'Failed to delete invoice',
    failedToFetchInvoices: 'Failed to fetch invoices',
    billTo: 'Bill To',
    unitPrice: 'Unit Price',
    quantity: 'Quantity',
    invoiceDownloaded: 'Invoice downloaded successfully',
    failedToGeneratePDF: 'Failed to generate PDF',
    pendingPayments: 'Pending Payments',
  },
  fr: {
    // General
    dashboard: 'Tableau de Bord',
    clients: 'Clients',
    products: 'Produits',
    invoices: 'Factures',
    quotes: 'Devis',
    expenses: 'Dépenses',
    reports: 'Rapports',
    aiAssistant: 'Assistant IA',
    settings: 'Paramètres',
    logout: 'Déconnexion',
    search: 'Rechercher',
    add: 'Ajouter',
    edit: 'Modifier',
    delete: 'Supprimer',
    cancel: 'Annuler',
    save: 'Enregistrer',
    create: 'Créer',
    update: 'Mettre à jour',
    actions: 'Actions',
    status: 'Statut',
    all: 'Tous',
    name: 'Nom',
    email: 'Email',
    phone: 'Téléphone',
    address: 'Adresse',
    city: 'Ville',
    country: 'Pays',
    date: 'Date',
    amount: 'Montant',
    total: 'Total',
    description: 'Description',
    category: 'Catégorie',
    loading: 'Chargement...',
    noResults: 'Aucun résultat trouvé',
    success: 'Succès',
    error: 'Erreur',
    confirm: 'Confirmer',
    view: 'Voir',
    download: 'Télécharger',
    optional: 'Optionnel',
    draft: 'Brouillon',
    selectFile: 'Sélectionner un Fichier',
    openMenu: 'Ouvrir le menu',
    currency: 'Devise',
    notes: 'Notes',
    price: 'Prix',
    confirmDeletion: 'Confirmer la Suppression',
    actionCannotBeUndone: 'Cette action ne peut pas être annulée.',
    tryAgain: 'Réessayer',
    
    // Dashboard
    welcomeBack: 'Bienvenue',
    hereIsWhatsHappening: 'Voici ce qui se passe avec votre entreprise',
    fromLastMonth: 'par rapport au mois dernier',
    newThisMonth: 'nouveaux ce mois-ci',
    createdThisMonth: 'créées ce mois-ci',
    overdueInvoices: 'factures en retard',
    recentInvoices: 'Factures Récentes',
    noRecentInvoices: 'Aucune facture récente',
    viewAllInvoices: 'Voir toutes les factures',
    aiInsights: 'Analyses IA',
    personalizedBusinessRecommendations: 'Recommandations commerciales personnalisées',
    generatingInsights: 'Génération d\'analyses...',
    noInsightsYet: 'Pas encore d\'analyses. Générez des analyses pour aider votre entreprise à se développer.',
    generateInsights: 'Générer des Analyses',
    quickActions: 'Actions Rapides',
    viewReports: 'Voir les Rapports',
    failedToLoadDashboard: 'Échec du chargement des données du tableau de bord',
    failedToGenerateInsights: 'Échec de la génération des analyses',
    premiumPlan: 'Plan Premium',
    businessPlan: 'Plan Business',
    freePlan: 'Plan Gratuit',
    
    // Admin
    adminDashboard: 'Tableau de Bord Admin',
    userManagement: 'Gestion des Utilisateurs',
    analytics: 'Analytiques',
    users: 'Utilisateurs',
    addUser: 'Ajouter un Utilisateur',
    
    // Clients
    addClient: 'Ajouter un Client',
    editClient: 'Modifier le Client',
    manageClientsInfo: 'Gérer vos clients et leurs informations',
    totalClients: 'Total des Clients',
    noClientsFound: 'Aucun client trouvé',
    clientCreatedSuccessfully: 'Client créé avec succès',
    clientUpdatedSuccessfully: 'Client mis à jour avec succès',
    clientDeletedSuccessfully: 'Client supprimé avec succès',
    failedToCreateClient: 'Échec de la création du client',
    failedToUpdateClient: 'Échec de la mise à jour du client',
    failedToDeleteClient: 'Échec de la suppression du client',
    failedToFetchClients: 'Échec de la récupération des clients',
    fillClientDetails: 'Remplissez les détails pour créer un nouveau client',
    updateClientDetails: 'Mettre à jour les informations du client',
    areYouSureDeleteClient: 'Êtes-vous sûr de vouloir supprimer le client',
    taxId: 'Numéro de TVA',
    paymentTerms: 'Conditions de Paiement',
    days: 'jours',
    discount: 'Remise',
    location: 'Emplacement',
    
    // Products
    addProduct: 'Ajouter un Produit',
    editProduct: 'Modifier le Produit',
    manageProductsInfo: 'Gérer vos produits et inventaire',
    totalProducts: 'produits au total',
    noProductsFound: 'Aucun produit trouvé',
    productCreatedSuccessfully: 'Produit créé avec succès',
    productUpdatedSuccessfully: 'Produit mis à jour avec succès',
    productDeletedSuccessfully: 'Produit supprimé avec succès',
    failedToCreateProduct: 'Échec de la création du produit',
    failedToUpdateProduct: 'Échec de la mise à jour du produit',
    failedToDeleteProduct: 'Échec de la suppression du produit',
    failedToFetchProducts: 'Échec de la récupération des produits',
    fillProductDetails: 'Remplissez les détails pour créer un nouveau produit',
    updateProductDetails: 'Mettre à jour les informations du produit',
    areYouSureDeleteProduct: 'Êtes-vous sûr de vouloir supprimer le produit',
    unit: 'Unité',
    taxRate: 'Taux de Taxe',
    sku: 'Référence',
    stock: 'Stock',
    currentStock: 'Stock Actuel',
    minimumStock: 'Stock Minimum',
    cost: 'Coût',
    active: 'Actif',
    
    // Quotes
    createQuote: 'Créer un Devis',
    quoteNumber: 'Numéro de Devis',
    quoteDate: 'Date du Devis',
    validUntil: 'Valable Jusqu\'au',
    quoteStatus: 'Statut',
    quoteAmount: 'Montant',
    quoteItems: 'Éléments du Devis',
    manageQuotes: 'Créer et gérer des devis pour vos clients',
    totalQuotes: 'devis au total',
    pending: 'En attente',
    accepted: 'Accepté',
    rejected: 'Rejeté',
    expired: 'Expiré',
    quoteDeletedSuccessfully: 'Devis supprimé avec succès',
    failedToDeleteQuote: 'Échec de la suppression du devis',
    failedToFetchQuotes: 'Échec de la récupération des devis',
    areYouSureDeleteQuote: 'Êtes-vous sûr de vouloir supprimer le devis',
    quoteDownloaded: 'Devis téléchargé avec succès',
    failedToGenerateQuotePDF: 'Échec de la génération du PDF du devis',
    
    // Expenses
    addExpense: 'Ajouter une Dépense',
    expenseDate: 'Date de la Dépense',
    expenseCategory: 'Catégorie',
    expenseAmount: 'Montant',
    paymentMethod: 'Méthode de Paiement',
    viewReceipt: 'Voir le Reçu',
    manageExpenses: 'Suivre et gérer vos dépenses professionnelles',
    totalExpensesCount: 'dépenses au total',
    expense: 'dépense',
    expenseFound: 'dépense trouvée',
    expensesFound: 'dépenses trouvées',
    expenseDeletedSuccessfully: 'Dépense supprimée avec succès',
    failedToDeleteExpense: 'Échec de la suppression de la dépense',
    failedToFetchExpenses: 'Échec de la récupération des dépenses',
    areYouSureDeleteExpense: 'Êtes-vous sûr de vouloir supprimer cette dépense',
    uploadReceipt: 'Téléverser un Reçu',
    downloadReceipt: 'Télécharger le Reçu',
    receiptUploaded: 'Reçu téléversé avec succès',
    failedToUploadReceipt: 'Échec du téléversement du reçu',
    
    // Reports
    financialReports: 'Rapports Financiers',
    salesReports: 'Rapports des Ventes',
    clientReports: 'Rapports Clients',
    revenueReport: 'Rapport de Revenus',
    expenseReport: 'Rapport de Dépenses',
    profitReport: 'Rapport de Profits',
    clientReport: 'Rapport Client',
    generateReport: 'Générer un Rapport',
    totalSales: 'Ventes Totales',
    totalExpenses: 'Dépenses Totales',
    profit: 'Bénéfice',
    profitMargin: 'Marge Bénéficiaire',
    salesOverTime: 'Ventes au Fil du Temps',
    expensesOverTime: 'Dépenses au Fil du Temps',
    salesTrend: 'Tendance des Ventes',
    expensesTrend: 'Tendance des Dépenses',
    monthlySales: 'Ventes Mensuelles',
    salesByMonth: 'Ventes par Mois',
    productSales: 'Ventes de Produits',
    salesByProduct: 'Ventes par Produit',
    clientRevenue: 'Revenus par Client',
    revenueByClient: 'Revenus par Client',
    clientDistribution: 'Distribution des Clients',
    revenueDistribution: 'Distribution des Revenus',
    months: 'Mois',
    year: 'Année',
    
    // AI Assistant
    generateContent: 'Générer du Contenu',
    contentType: 'Type de Contenu',
    prompt: 'Requête',
    context: 'Contexte',
    recentGenerations: 'Générations Récentes',
    copyToClipboard: 'Copier dans le Presse-papiers',
    copied: 'Copié!',
    emailTemplate: 'Modèle d\'Email',
    marketingCopy: 'Texte Marketing',
    productDescription: 'Description de Produit',
    socialMediaPost: 'Publication sur les Réseaux Sociaux',
    blogPost: 'Article de Blog',
    customContent: 'Contenu Personnalisé',
    generate: 'Générer',
    generatingContent: 'Génération de Contenu...',
    generatedOn: 'Généré le',
    
    // Invoice related
    createInvoice: 'Créer une Facture',
    manageInvoicesAndTrackPayments: 'Gérer vos factures et suivre les paiements',
    invoiceNumber: 'Facture #',
    client: 'Client',
    dueDate: 'Date d\'échéance',
    allInvoices: 'Toutes les Factures',
    allStatuses: 'Tous les Statuts',
    filterByStatus: 'Filtrer par statut',
    youHave: 'Vous avez',
    totalInvoices: 'Total des Factures',
    noInvoicesFound: 'Aucune facture trouvée',
    downloadPDF: 'Télécharger PDF',
    sent: 'Envoyée',
    paid: 'Payée',
    overdue: 'En retard',
    cancelled: 'Annulée',
    areYouSureDelete: 'Êtes-vous sûr de vouloir supprimer la facture',
    invoiceDeletedSuccessfully: 'Facture supprimée avec succès',
    failedToDeleteInvoice: 'Échec de la suppression de la facture',
    failedToFetchInvoices: 'Échec de la récupération des factures',
    billTo: 'Facturer à',
    unitPrice: 'Prix unitaire',
    quantity: 'Quantité',
    invoiceDownloaded: 'Facture téléchargée avec succès',
    failedToGeneratePDF: 'Échec de la génération du PDF',
    pendingPayments: 'Paiements en Attente',
  }
};

// Create context
interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Provider component
interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  // Translation function
  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

// Custom hook to use the language context
export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}; 